In [ ]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Pardhasaradhi\OneDrive\Documents\GitHub\apple-stock-analysis\dataset\AAPL.csv")
print(df)

             Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.100178
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.094952
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.087983
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.090160
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092774
...           ...         ...         ...         ...         ...         ...
10463  2022-06-13  132.869995  135.199997  131.440002  131.880005  131.880005
10464  2022-06-14  133.130005  133.889999  131.479996  132.759995  132.759995
10465  2022-06-15  134.289993  137.339996  132.160004  135.429993  135.429993
10466  2022-06-16  132.080002  132.389999  129.039993  130.059998  130.059998
10467  2022-06-17  130.070007  133.080002  129.809998  131.559998  131.559998

          Volume
0      469033600
1      175884800
2      105728000
3       86441600
4       73449600
...          ...
10463  122207100
10464   84784300
10465   91533000
10466  108123900
10467  134118500

[10468 rows x 7 columns]

In [4]:
df.shape

(10468, 7)

In [5]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10468 entries, 0 to 10467
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10468 non-null  str
 1   Open       10468 non-null  float64
 2   High       10468 non-null  float64
 3   Low        10468 non-null  float64
 4   Close      10468 non-null  float64
 5   Adj Close  10468 non-null  float64
 6   Volume     10468 non-null  int64
dtypes: float64(5), int64(1), str(1)
memory usage: 572.6 KB

In [7]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,10468.000000,10468.000000,10468.000000,10468.000000,10468.000000,1.046800e+04
mean,14.757987,14.921491,14.594484,14.763533,14.130431,3.308489e+08
std,31.914174,32.289158,31.543959,31.929489,31.637275,3.388418e+08
min,0.049665,0.049665,0.049107,0.049107,0.038329,0.000000e+00
25%,0.283482,0.289286,0.276786,0.283482,0.235462,1.237768e+08
50%,0.474107,0.482768,0.465960,0.475446,0.392373,2.181592e+08
75%,14.953303,15.057143,14.692589,14.901964,12.835269,4.105794e+08
max,182.630005,182.940002,179.119995,182.009995,181.511703,7.421641e+09

In [8]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')

In [12]:
df.head()

        Date      Open      High       Low     Close  Adj Close     Volume
0 1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100178  469033600
1 1980-12-15  0.122210  0.122210  0.121652  0.121652   0.094952  175884800
2 1980-12-16  0.113281  0.113281  0.112723  0.112723   0.087983  105728000
3 1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090160   86441600
4 1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092774   73449600

In [13]:
df.corr()

,Date,Open,High,Low,Close,Adj Close,Volume
Date,1.000000,0.644481,0.644066,0.644904,0.644475,0.630630,0.166282
Open,0.644481,1.000000,0.999943,0.999924,0.999850,0.999516,-0.196211
High,0.644066,0.999943,1.000000,0.999908,0.999924,0.999618,-0.195635
Low,0.644904,0.999924,0.999908,1.000000,0.999928,0.999575,-0.197150
Close,0.644475,0.999850,0.999924,0.999928,1.000000,0.999671,-0.196411
Adj Close,0.630630,0.999516,0.999618,0.999575,0.999671,1.000000,-0.199262
Volume,0.166282,-0.196211,-0.195635,-0.197150,-0.196411,-0.199262,1.000000

In [ ]:
plt.figure(figsize=(15, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()